(() => {
  "use strict";

  /*
   * Draw On My Face - signed clear-only pixels.js
   *
   * NO drawing
   * NO pointer handling
   * NO pixel storage
   * NO pixel fading
   * NO pixel batching
   *
   * Only accepts cryptographically signed CLEAR commands.
   */

  const PIXEL_CHANNEL = "pixels";

  // ============================================================
  // ED25519 PUBLIC KEY
  // ============================================================
  //
  // Put the BASE64 public key generated by generate_keys.py here.
  //
  const PUBLIC_KEY_B64 =
    "PUT_PUBLIC_KEY_HERE";

  // Commands older than this are rejected.
  const MAX_COMMAND_AGE_MS = 30_000;

  // Prevent replaying the exact same command.
  const usedNonces = new Set();

  let pubnub = null;
  let canvas = null;
  let context = null;
  let subscribed = false;

  // ============================================================
  // BASE64 HELPERS
  // ============================================================

  function base64ToBytes(base64) {
    const binary = atob(base64);

    const bytes = new Uint8Array(binary.length);

    for (let i = 0; i < binary.length; i++) {
      bytes[i] = binary.charCodeAt(i);
    }

    return bytes;
  }

  function bytesToBase64(bytes) {
    let binary = "";

    for (const byte of bytes) {
      binary += String.fromCharCode(byte);
    }

    return btoa(binary);
  }

  // ============================================================
  // CANVAS
  // ============================================================

  function acquireCanvas() {
    if (canvas && context) {
      return true;
    }

    const element = document.getElementById("canvas");

    if (!element) {
      return false;
    }

    canvas = element;
    context = element.getContext("2d");

    return !!context;
  }

  // ============================================================
  // CLEAR CANVAS
  // ============================================================

  function clearCanvas() {
    if (!acquireCanvas()) {
      return;
    }

    context.clearRect(
      0,
      0,
      canvas.width,
      canvas.height
    );

    console.log(
      "[DrawOnMyFace] VALID SIGNATURE - canvas cleared"
    );
  }

  // ============================================================
  // BUILD SIGNED DATA
  // ============================================================
  //
  // Python signs exactly:
  //
  // clear|timestamp|nonce
  //
  // The browser reconstructs exactly the same string.
  // ============================================================

  function signedPayload(timestamp, nonce) {
    return `clear|${timestamp}|${nonce}`;
  }

  // ============================================================
  // VERIFY ED25519
  // ============================================================
  //
  // Uses the browser's native Web Crypto API.
  // ============================================================

  async function verifySignature(
    timestamp,
    nonce,
    signatureB64
  ) {
    try {
      const publicKeyBytes =
        base64ToBytes(PUBLIC_KEY_B64);

      const signatureBytes =
        base64ToBytes(signatureB64);

      const data = new TextEncoder().encode(
        signedPayload(timestamp, nonce)
      );

      /*
       * Ed25519 support is available in modern browsers.
       */
      const publicKey =
        await crypto.subtle.importKey(
          "raw",
          publicKeyBytes,
          {
            name: "Ed25519"
          },
          false,
          ["verify"]
        );

      return await crypto.subtle.verify(
        {
          name: "Ed25519"
        },
        publicKey,
        signatureBytes,
        data
      );

    } catch (error) {
      console.error(
        "[DrawOnMyFace] signature verification failed:",
        error
      );

      return false;
    }
  }

  // ============================================================
  // VALIDATE CLEAR COMMAND
  // ============================================================

  async function handleClearCommand(message) {
    if (!message) {
      return;
    }

    if (message.type !== "clear") {
      return;
    }

    if (
      typeof message.timestamp !== "number" ||
      typeof message.nonce !== "string" ||
      typeof message.signature !== "string"
    ) {
      console.warn(
        "[DrawOnMyFace] malformed clear command"
      );

      return;
    }

    const now = Date.now();

    const age =
      Math.abs(now - message.timestamp);

    if (age > MAX_COMMAND_AGE_MS) {
      console.warn(
        "[DrawOnMyFace] expired clear command"
      );

      return;
    }

    if (usedNonces.has(message.nonce)) {
      console.warn(
        "[DrawOnMyFace] replayed clear command"
      );

      return;
    }

    const valid =
      await verifySignature(
        message.timestamp,
        message.nonce,
        message.signature
      );

    if (!valid) {
      console.warn(
        "[DrawOnMyFace] INVALID clear signature"
      );

      return;
    }

    usedNonces.add(message.nonce);

    // Keep memory bounded.
    if (usedNonces.size > 1000) {
      const first =
        usedNonces.values().next().value;

      usedNonces.delete(first);
    }

    clearCanvas();
  }

  // ============================================================
  // PUBNUB
  // ============================================================

  function acquirePubNub() {
    if (pubnub) {
      return true;
    }

    if (
      typeof window.PubNub !== "function"
    ) {
      return false;
    }

    pubnub = window.PubNub({});

    return true;
  }

  function subscribe() {
    if (!acquirePubNub()) {
      return;
    }

    if (subscribed) {
      return;
    }

    pubnub.subscribe({
      channel: PIXEL_CHANNEL,
      messages: handleClearCommand
    });

    subscribed = true;

    console.log(
      "[DrawOnMyFace] signed clear listener active"
    );
  }

  // ============================================================
  // INITIALIZATION
  // ============================================================

  function initialize() {
    acquireCanvas();
    subscribe();
  }

  initialize();

  document.addEventListener(
    "DOMContentLoaded",
    initialize
  );

  // ============================================================
  // PUBLIC API
  // ============================================================

  window.DrawOnMyFace = {
    clearLocal: clearCanvas
  };

})();
